# This file was generated by project setup to hold shared variables for project KiVa (Kiusaamista Vastaan) Primary School Anti-bullying Program in Czech Republic: Evaluation of Effectiveness and Fidelity.
# It is loaded by default by each RMarkdown file created using reschola's templates.
# You should add all variables needed in multiple scripts here.

# Do not add passwords, API keys and other information that should not be made public.

# Store those in .Renviron. usethis::edit_r_environ() opens it for you for editing.
project_title <- "KiVa (Kiusaamista Vastaan) Primary School Anti-bullying Program in Czech Republic: Evaluation of Effectiveness and Fidelity"
gd_url <- ""
